name: Development

on: push
# TODO change to pull_request

jobs:
  tests:
    name: Build and Test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: load cached node_modules
        uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: node-${{ hashFiles('**/package-lock.json')}}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build
        run: npm run build

      - name: Tests
        run: npm run test -- --ci

      - name: Codecov
        uses: codecov/codecov-action@v1.5.0
